### ISSUE TITLE
Chan必须在协程中才能>>输出

### ISSUE THREAD

**Issue by dtspmt** [idealvin/coost#245]
v2.03 vs2019 win 64位
https://coostdocs.github.io/cn/about/co/
中Chan的例子，运行后会报 check failed: s! must be called in coroutine.
而unitest/co.cc里，是在协程中>>
linux环境没试，是不是Chan的输入输出都必须在协程里？还是win、linux有差异？

**Comment by idealvin** [comment]
可以看看[参考文档](https://coostdocs.gitee.io/cn/co/coroutine/#operator)

**Comment by dtspmt** [comment]
参考文档的例子运行也有问题
![image](https://user-images.githubusercontent.com/42854063/180142372-e83303d7-a3fe-40af-83e6-c31d5c7f1e54.png)
必须要用go([wg]() { xxx>> xx; wg.done();})才有效

**Comment by idealvin** [comment]
@dtspmt  `Chan` 目前只适用于协程，这个在文档里有明确说明。

**Comment by dtspmt** [comment]
我的问题，没有把main协程化
