### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tarma** [idealvin/coost#247]
The API in JSON module described in the docs are not compatible in the latest release version(2.0.3).

I hope there could be a new release version and upload to conan. Thank you.

**Comment by idealvin** [comment]
> The API in JSON module described in the docs are not compatible in the latest release version(2.0.3).
> 
> I hope there could be a new release version and upload to conan. Thank you.

Yes, we'll do it. On the way.

**Comment by prince-chrismc** [comment]
@idealvin ConanCenter community is trying to add the latest release but there's a question when you have a minute 

https://github.com/conan-io/conan-center-index/pull/12383

**Comment by idealvin** [comment]
> @idealvin ConanCenter community is trying to add the latest release but there's a question when you have a minute
> 
> [conan-io/conan-center-index#12383](https://github.com/conan-io/conan-center-index/pull/12383)

@prince-chrismc  We'll release a new version of Coost in the following days.

**Comment by prince-chrismc** [comment]
Should ConanCenter rename `cocoyaxi` to `coost`?

**Comment by idealvin** [comment]
@prince-chrismc  sorry, a little busy these days.

**Comment by idealvin** [comment]
@tarma @prince-chrismc 

coost v3.0.0 has been released [here](https://github.com/idealvin/coost/releases/tag/v3.0.0).
