### ISSUE TITLE
是否可以在线程中调度协程? 我有redis异步客户端, 在协程中请求redis异步返回后直接调用yield, 异步客户端的callback中(非协程中执行)调度当时yield的协程

### ISSUE THREAD

**Issue by jiangdongzi** [idealvin/coost#248]
这样可以吗, 如果可以的话, 是不是只要客户端是异步的, 就可以在不hook的前提下使用协程

**Comment by idealvin** [comment]
可以参考[这里](https://coostdocs.gitee.io/cn/co/coroutine/#%E5%8D%8F%E7%A8%8B%E5%8C%96)

**Comment by jiangdongzi** [comment]
> 可以参考[这里](https://coostdocs.gitee.io/cn/co/coroutine/#%E5%8D%8F%E7%A8%8B%E5%8C%96)

这个文档我详细看了，一自己协程化三方网络库，二，hook，hook是全局的，总觉得不安全。而我说的这种方式，是只要可以找到异步客户端(支持回调， 就可以轻松改造成支持协程的客户端。 我看了源码，需要使用g_sched->running()这个函数，但是并没有暴露出来。

**Comment by jiangdongzi** [comment]
本质就是可以调用到add_ready_task()就可以了

**Comment by jiangdongzi** [comment]
搜狗开源的workflow支持redis，mysql，kafka异步客户端，结合这个协程库，可以轻松协程化这三个客户端

**Comment by jiangdongzi** [comment]
@idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 这样就集成了. 你觉得呢

**Comment by idealvin** [comment]
> @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢

这样是可以的，可以贴下代码，看看还需要暴露哪些接口

**Comment by jiangdongzi** [comment]
> > @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢
> 
> 这样是可以的，可以贴下代码，看看还需要暴露哪些接口

我用add_ready_task实现啦, 目前不用暴露了. 不过如果可以封装成比如signal唤醒更合适一些.

**Comment by Barenboim** [comment]
> > > @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢
> > 
> > 
> > 这样是可以的，可以贴下代码，看看还需要暴露哪些接口
> 
> 我用add_ready_task实现啦, 目前不用暴露了. 不过如果可以封装成比如signal唤醒更合适一些.

😳
能不能开源一下实现。如果给workflow搞协程，可以把series对用户隐藏，series context用来存放协程上下文。

**Comment by idealvin** [comment]
> > > @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢
> > 
> > 
> > 这样是可以的，可以贴下代码，看看还需要暴露哪些接口
> 
> 我用add_ready_task实现啦, 目前不用暴露了. 不过如果可以封装成比如signal唤醒更合适一些.

已经增加了 `co::coroutine()`, `co::resume()` 两个接口，具体用法见 [test/yield.cc](https://github.com/idealvin/coost/blob/master/test/yield.cc).

**Comment by Barenboim** [comment]
@jiangdongzi

**Comment by lasorda** [comment]
> > > > @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢
> > > 
> > > 
> > > 这样是可以的，可以贴下代码，看看还需要暴露哪些接口
> > 
> > 
> > 我用add_ready_task实现啦, 目前不用暴露了. 不过如果可以封装成比如signal唤醒更合适一些.
> 
> 😳 能不能开源一下实现。如果给workflow搞协程，可以把series对用户隐藏，series context用来存放协程上下文。

搜狗的workflow和[https://github.com/taskflow/taskflow](https://github.com/taskflow/taskflow)，这两个区别在哪里，taskflow是不是更抽象一些

**Comment by Barenboim** [comment]
> > > > > @idealvin 我觉得可以调用异步客户端返回后直接yield, 以在call_back(异步客户端框架的线程中)中调用唤醒. 不过我是直接在call_back中调用了add_ready_task. 这样就集成了. 你觉得呢
> > > > 
> > > > 
> > > > 这样是可以的，可以贴下代码，看看还需要暴露哪些接口
> > > 
> > > 
> > > 我用add_ready_task实现啦, 目前不用暴露了. 不过如果可以封装成比如signal唤醒更合适一些.
> > 
> > 
> > 😳 能不能开源一下实现。如果给workflow搞协程，可以把series对用户隐藏，series context用来存放协程上下文。
> 
> 搜狗的workflow和https://github.com/taskflow/taskflow，这两个区别在哪里，taskflow是不是更抽象一些

workflow是计算+网络， taskflow只做计算调度吧。
