### ISSUE TITLE
http server close之后无法再次开启

### ISSUE THREAD

**Issue by BiaoGe2399** [idealvin/coost#250]
MFC调用的GUI程序，测试开启后执行close再开一次就会闪退。

**Comment by BiaoGe2399** [comment]
还有怎么判断我是否开启成功了？如果端口被其他程序占用了呢，应该有个返回值或者参数说明一下。

**Comment by idealvin** [comment]
> 还有怎么判断我是否开启成功了？如果端口被其他程序占用了呢，应该有个返回值或者参数说明一下。

目前的设计，没有返回值，服务启动失败就让程序挂掉。

按目前的设计，HTTP server 启动后，`http::Server`对象就没有用了。
```cpp
http::Server().on_req(cb).start("0.0.0.0", 80);
```
