### ISSUE TITLE
xmake如何指定vs版本？

### ISSUE THREAD

**Issue by dragon-dan** [idealvin/coost#263]
电脑上安装了多个版本vs（VS2022、VS2019、VS2015、VS2010），按照文档用xmake编译，好像一直都是用的VS2022进行编译，没办法切换VS版本。用cmake尝试，可以指定需要版本的vs，似乎报libcurl相关的问题。希望大佬指点一下怎么弄

**Comment by idealvin** [comment]
可以试试用 `xmake --sdk=/path/to/vs` 指定 vs 所在目录

**Comment by waruqi** [comment]
xmake f --vs=2019 -c

**Comment by dragon-dan** [comment]
> 可以试试用 `xmake --sdk=/path/to/vs` 指定 vs 所在目录, [xmake文档](https://xmake.io/#/zh-cn/toolchain/builtin_toolchains)

--sdk指定，我试了半天不太好使，怎么指定目录都不行，--vs=2019这个有效
