### ISSUE TITLE
在 Ubuntu x86_64 上交叉编译 coost 时，出现缺少工具链的问题

### ISSUE THREAD

**Issue by hyena04** [idealvin/coost#266]
我在Ubuntu x86_64上交叉编译coost时出现缺少工具链的问题，求帮助。

我首先安装了arm交叉编译工具

`sudo apt-get install g++-10-multilib-arm-linux-gnueabi gcc-10-multilib-arm-linux-gnueabi gcc-10-plugin-dev-arm-linux-gnueabi`

然后使用如下命令进行coost配置

`xmake f --with_openssl=false --with_libcurl=false --host=linux -k static -m debug -a arm -p cross --cc=arm-linux-gnueabi-gcc-10 --cxx=arm-linux-gnueabi-g++-10 -vD libco`

命令的输出如下

`checking for arm-linux-gnueabi-gcc-10 ... /usr/bin/arm-linux-gnueabi-gcc-10
checking for arm-linux-gnueabi-g++-10 ... /usr/bin/arm-linux-gnueabi-g++-10
checking for flags (-fPIC) ... ok
> arm-linux-gnueabi-gcc-10 "-fPIC"
> arm-linux-gnueabi-gcc-10 -c -o /dev/shm/.xmake1000/220929/_627C79C8BE294D208A6504E3291CE240.o /dev/shm/.xmake1000/220929/_63129F2A62AA49F2BE505CE0966A4300.c
checking for flags (-fPIC) ... ok
> arm-linux-gnueabi-g++-10 "-fPIC"
> arm-linux-gnueabi-g++-10 -c -o /dev/shm/.xmake1000/220929/_03379E9946334D20825C91B1C3D01050.o /dev/shm/.xmake1000/220929/_2EB2C5E08EF94E7EBD1C7CF990F2A1F0.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> arm-linux-gnueabi-gcc-10 "-fdiagnostics-color=always"
checking for flags (-fdiagnostics-color=always) ... ok
> arm-linux-gnueabi-g++-10 "-fdiagnostics-color=always"
> checking for c includes(backtrace.h)
checking for libbacktrace ... ok
> checking for c++ includes(cxxabi.h)
checking for cxxabi ... ok
generating include/co/config.h.in to build/../include/co/config.h ..
checking for git ... /usr/bin/git
  > replace COOST_SHARED -> 0
generating include/co/config.h.in ... cache
error: @programdir/core/main.lua:280: @programdir/actions/config/main.lua:158: target(stack): toolchain not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:882]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:181]: in function 'assert'
    [@programdir/actions/config/main.lua:158]: in function '_check_target_toolchains'
    [@programdir/actions/config/main.lua:442]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:882: in function 'base/os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:280: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>`

**Comment by idealvin** [comment]
可以参考 ruki 写的[这篇文章](https://zhuanlan.zhihu.com/p/96031862)，用下面的试试：
```sh
$ xmake f -p cross --sdk=/home/toolchains_sdkdir 
$ xmake
```

**Comment by hyena04** [comment]
修改使用如下命令进行coost配置

`xmake f --with_openssl=false --with_libcurl=false -k static -m debug -a arm --target_os=linux --cc=arm-linux-gnueabi-gcc-10 --cxx=arm-linux-gnueabi-g++-10 --sdk=/usr/arm-linux-gnueabi -vD`

输出如下

`checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for arm-linux-gnueabi-gcc-10 ... /usr/bin/arm-linux-gnueabi-gcc-10
checking for arm-linux-gnueabi-g++-10 ... /usr/bin/arm-linux-gnueabi-g++-10
checking for flags (-fPIC) ... ok
> arm-linux-gnueabi-gcc-10 "-fPIC"
> arm-linux-gnueabi-gcc-10 -c -o /dev/shm/.xmake1000/221009/_DBCF14222ABF4600818BB08FD013E330.o /dev/shm/.xmake1000/221009/_63129F2A62AA49F2BE505CE0966A4300.c
checking for flags (-fPIC) ... ok
> arm-linux-gnueabi-g++-10 "-fPIC"
> arm-linux-gnueabi-g++-10 -c -o /dev/shm/.xmake1000/221009/_DB30E23B27144B108264B94A3F89BF10.o /dev/shm/.xmake1000/221009/_2EB2C5E08EF94E7EBD1C7CF990F2A1F0.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> arm-linux-gnueabi-gcc-10 "-fdiagnostics-color=always"
checking for flags (-fdiagnostics-color=always) ... ok
> arm-linux-gnueabi-g++-10 "-fdiagnostics-color=always"
> checking for c includes(backtrace.h)
checking for libbacktrace ... ok
> checking for c++ includes(cxxabi.h)
checking for cxxabi ... ok
generating include/co/config.h.in to build/../include/co/config.h ..
checking for git ... /usr/bin/git
  > replace COOST_SHARED -> 0
generating include/co/config.h.in ... cache
configure
{
    mode = debug
    ccache = true
    buildir = build
    with_libcurl = false
    host = linux
    plat = linux
    cxxabi = true
    fpic = false
    target_os = linux
    arch = arm
    ndk_stdcxx = true
    cc = arm-linux-gnueabi-gcc-10
    with_openssl = false
    sdk = /usr/arm-linux-gnueabi
    kind = static
    libbacktrace = true
    cxx = arm-linux-gnueabi-g++-10
}
`

然后进行构建

`xmake build -vD --all`

构建出现错误

`[ 80%]: linking.debug wg
/usr/bin/g++ -o build/linux/arm/debug/wg build/.objs/wg/linux/arm/debug/test/wg.cc.o -Lbuild/linux/arm/debug -lco -lbacktrace -lpthread -ldl
[ 80%]: linking.debug flag
/usr/bin/g++ -o build/linux/arm/debug/flag build/.objs/flag/linux/arm/debug/test/flag.cc.o -Lbuild/linux/arm/debug -lco -lbacktrace -lpthread -ldl
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/actions/build/kinds/binary.lua:74: @programdir/core/sandbox/modules/os.lua:267: /usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: build/.objs/err/linux/arm/debug/test/err.cc.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:882]:
    [@programdir/core/sandbox/modules/os.lua:267]: in function 'runv'
    [@programdir/modules/core/tools/gcc.lua:377]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/actions/build/kinds/binary.lua:74]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:193]: in function 'on_changed'
    [@programdir/actions/build/kinds/binary.lua:55]: in function '_do_link_target'
    [@programdir/actions/build/kinds/binary.lua:102]:
    [@programdir/actions/build/kinds/binary.lua:129]: in function '_link_target'
    [@programdir/actions/build/kinds/binary.lua:157]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:882: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/modules/private/async/runjobs.lua:256: in field 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in global 'try'
	@programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>`

**Comment by waruqi** [comment]
ld 没设置。

另外走自动探测不行？ 工具链目录结构贴下。。

或者

```console
xmake f --with_openssl=false --with_libcurl=false -k static -m debug --cross=arm-linux-gnueabi-gcc-  -c -vD
```
