### ISSUE TITLE
How to configure the amount of threads used?

### ISSUE THREAD

**Issue by evonicgu** [idealvin/coost#267]
Documentation states, that FLG_co_sched_num must be used to configure the amount of threads. But it is not visible if I build the project with CMake.

**Comment by idealvin** [comment]
> Documentation states, that FLG_co_sched_num must be used to configure the amount of threads. But it is not visible if I build the project with CMake.

You may set it in command line:
```sh
-co_sched_num 4
```

or set it in the config file:

```sh
co_sched_num = 4
```

**Comment by evonicgu** [comment]
Is there any possibility to configure this parameter in rutime?

**Comment by evonicgu** [comment]
Let me explain the use case. I want to change the maximum amount of threads used by the scheduler during the startup of the program, because i want this parameter to be configurable through the cli.

**Comment by idealvin** [comment]
> Let me explain the use case. I want to change the maximum amount of threads used by the scheduler during the startup of the program, because i want this parameter to be configurable through the cli.

You may include co/flag.h, and use `flag::set_value("co_sched_num", "4")`

**Comment by evonicgu** [comment]
That works!! Thank you very much for you help and for this fantastic library. Closing the issue.
