### ISSUE TITLE
用百度ai的sdkJson库命名冲突

### ISSUE THREAD

**Issue by cgisky1980** [idealvin/coost#268]
用百度ai的sdk，里面引用了 jsoncpp，和co/Json 命名起冲突 。建议都放到co命名空间下吧

**Comment by akofer** [comment]
@idealvin 老兄是咋看这种问题？如果项目想要被广泛使用，名字污染还是得避免掉，牺牲一点点简洁。。。

**Comment by idealvin** [comment]
已经移除了全局的 `Json`，可以用 `json::Json` 或 `co::Json`
