### ISSUE TITLE
最新版的源代码中没找到Hook的相关设置

### ISSUE THREAD

**Issue by 1027663760** [idealvin/coost#276]
https://coostdocs.gitee.io/cn/co/coroutine/#disable_hook_sleep

hook_win.cc 里面没这个了，现在是强制要Hook吗？

**Comment by 1027663760** [comment]
现在是在这里设置？

![1](https://user-images.githubusercontent.com/26378634/202593217-d6b15d43-fc51-4954-944d-a68c301fb445.png)

**Comment by idealvin** [comment]
http client相关的代码需要 hook，编译时全局定义 `_CO_DISABLE_HOOK` 宏可以禁用 hook，但 http client 相关的功能就不能使用。

**Comment by 1027663760** [comment]
> _CO_DISABLE_HOOK

这个怎么定义，我用的是xmake编译。。

**Comment by idealvin** [comment]
coost  src/xmake.lua  里加一个全局的宏定义：
```lua
add_defines("_CO_DISABLE_HOOK")
```

**Comment by 1027663760** [comment]
> coost 根目录xmake.lua 里加一个全局的宏定义：
> 
> ```lua
> add_defines("_CO_DISABLE_HOOK")
> ```

感谢！还有没有其它可自定义宏呢...比如我只想要编译协程应该怎么设置(最精简体积)

**Comment by idealvin** [comment]
这个暂时没有

**Comment by 1027663760** [comment]
> 这个暂时没有

好吧，希望以后能专门弄一个定义各种功能宏设置的地方，这样方便按需调整...
