### ISSUE TITLE
tasked声明顺序

### ISSUE THREAD

**Issue by aijle** [idealvin/coost#277]
Thread _t 要放在最后声明，否则启动时可能会崩溃。

**Comment by idealvin** [comment]
> Thread _t 要放在最后声明，否则启动时可能会崩溃。

感谢指出这个问题

**Comment by yangjuncode** [comment]
@aijle @idealvin  请问下这个是什么道理，为啥声明顺序都能出现这样的问题？

**Comment by idealvin** [comment]
> @aijle @idealvin 请问下这个是什么道理，为啥声明顺序都能出现这样的问题？

线程启动后引用了未初始化的对象

**Comment by yangjuncode** [comment]
> > @aijle @idealvin 请问下这个是什么道理，为啥声明顺序都能出现这样的问题？
> 
> 线程启动后引用了未初始化的对象

嗯，下面这个点倒是忘记了。
```
C++ 初始化类成员时，是按照声明的顺序初始化的，而不是按照出现在初始化列表中的顺序
```
