### ISSUE TITLE
chan中能否支持fastring类型

### ISSUE THREAD

**Issue by gswgit** [idealvin/coost#283]
这个库很好用，看了看相关文档，chan支持的类型为满足a = b 等价于 memcpy(&a, &b, sizeof(T))。

**Comment by gswgit** [comment]
chan能否支持实现了复制构造函数、赋值构造函数的自定义类型

**Comment by idealvin** [comment]
后面有空考虑支持

**Comment by idealvin** [comment]
master最新代码已支持
