### ISSUE TITLE
latest code tests hang for ever on x86-64 ubuntu and apple m1 arm64

### ISSUE THREAD

**Issue by akofer** [idealvin/coost#284]
在 macbook m1 下，顺利编译，但是测试挂在了 mem_test 那儿

~/coost/build $ make test
Running tests...
Test project /Users/pangu/codebase/coost/build
      Start  1: unitest
 1/35 Test  #1: unitest ..........................   Passed    0.45 sec
      Start  2: bm_test
 2/35 Test  #2: bm_test ..........................   Passed    0.37 sec
      Start  3: chan_test
 3/35 Test  #3: chan_test ........................   Passed    0.40 sec
      Start  4: closure_test
 4/35 Test  #4: closure_test .....................   Passed    0.36 sec
      Start  5: co_test
 5/35 Test  #5: co_test ..........................   Passed    0.78 sec
      Start  6: cout_test
 6/35 Test  #6: cout_test ........................   Passed    0.35 sec
      Start  7: defer_test
 7/35 Test  #7: defer_test .......................   Passed    0.39 sec
      Start  8: err_test
 8/35 Test  #8: err_test .........................   Passed    0.32 sec
      Start  9: fast_test
 9/35 Test  #9: fast_test ........................   Passed    0.39 sec
      Start 10: flag_test
10/35 Test #10: flag_test ........................   Passed    0.31 sec
      Start 11: go_test
11/35 Test #11: go_test ..........................   Passed    0.50 sec
      Start 12: json_test
12/35 Test #12: json_test ........................   Passed    0.42 sec
      Start 13: log_test
13/35 Test #13: log_test .........................   Passed    0.33 sec
      Start 14: maybe_test
14/35 Test #14: maybe_test .......................   Passed    0.33 sec
      Start 15: mem_test

**Comment by akofer** [comment]
找了台 x86-64 ubuntu22.04，也是挂在 mem_test。

以上测的 git master，又在mac和ubuntu上都测试了 tag v3.0，也是一样的现象。

**Comment by akofer** [comment]
挂起时的截图

<img width="309" alt="image" src="https://user-images.githubusercontent.com/7020530/210126200-5797ddfa-dffa-4ac7-81dd-ef55e2fa66c3.png">

**Comment by akofer** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/7020530/210126403-92996e72-3ee5-4049-85e1-9808b147ccd0.png">

看了下 mem.cc, 为啥测试里要 while(true) sleep...

**Comment by idealvin** [comment]
为了偷点懒..
