### ISSUE TITLE
avoid to use names with two leading underscores 

### ISSUE THREAD

**Issue by akofer** [idealvin/coost#288]
names with "__" as prefix are reserved for the c++ compiler & runtime.

details in c++ specification 2.10.3 (https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf)
<img width="880" alt="image" src="https://user-images.githubusercontent.com/7020530/210159175-4071f9ad-4973-454f-a553-d708a72e1bf8.png">

**Comment by akofer** [comment]
a possible solution likes google c++ code style's private member name: use _ as suffix instead of prefix.

**Comment by idealvin** [comment]
`_` 作后缀不利于编辑器的自动补全，影响敲代码的流畅性。

到目前为止，还没有人反馈因 coost 用 `_` 作前缀导致编译冲突的，这个问题暂不在考虑范围。

**Comment by akofer** [comment]
vscode 后缀也能补...

**Comment by idealvin** [comment]
已经尽可能按建议改名了
