### ISSUE TITLE
tcp::Client是否可以增加接口，可以绑定socket的ip

### ISSUE THREAD

**Issue by Z-eddy** [idealvin/coost#291]
使用环境：win10，单台PC有多个ip
需求：tcp::Client增加绑定ip和port的接口，类似这样：
```
bool bind(const std::string &address, quint16 port = 0);
```
使用效果：server可以通过peer看到bind的ip/port：
```
void on_connection(tcp::Connection conn) {
  auto socket{conn.socket()};
  // 此处的ip port为自定义绑定的
  auto ipPort= co::peer(socket);
}
```

**Comment by idealvin** [comment]
@Z-eddy  这个功能已经加上了，可以试试

**Comment by Z-eddy** [comment]
测试平台: win7
测试方法:分别使用qt的和coost的tcp进行测试
测试结果:qt的测试通过，coost的client异常
异常日志:sock_win.cc:156  connectex bind local address failed,sock:588
tcp.cc:510  connect to 173.177.23.36:8899 failed:An invalid argument was supplied
测试代码（非常抱歉，这是在局域网的测试，只能通过拍照进行展示）:
server:
![IMG_20230110_100658](https://user-images.githubusercontent.com/54835865/211445853-ca4c416a-ee86-42e7-998c-b99e11529870.jpg)
client:
![IMG_20230110_100738](https://user-images.githubusercontent.com/54835865/211445906-4689926b-5c77-453d-875b-a160071dd390.jpg)

**Comment by idealvin** [comment]
@Z-eddy 

windows上有点特殊，[这里](https://github.com/idealvin/coost/blob/master/src/co/sock_win.cc#L155) 需要修复一下，已经bind过一次，再次bind可能会返回 [WSAEADDRINUSE](https://learn.microsoft.com/en-us/windows/desktop/WinSock/windows-sockets-error-codes-2) 这个错误，忽略这个错误应该就可以了

**Comment by Z-eddy** [comment]
运行平台:win7
第一次尝试:重启电脑，第一次运行编译好的程序（没有进行第二次的bind操作）
存在问题:和上面的问题一模一样

第二次尝试:
sock_win.cc文件里:
注释掉你标注的157行:
return -1;

存在问题:
程序会阻塞在164行:
r = connect_ex(fd, (const sockaddr*)addr, addrlen, 0, 0, 0, &ev->ol);

**Comment by idealvin** [comment]
@Z-eddy 

这个问题并不难解决，已经bind addr的socket，不用再次bind，处理下就可以了。

[MS 官方文档](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-bind) 里有说明的，已经bind的 socket，再次调用bind会返回 `WSAEINVAL`，忽略掉这个错误就可以了

**Comment by idealvin** [comment]
@Z-eddy 

这个问题有点棘手，windows上用了IOCP，connect调用的是 connectex，在调用connectex前只能绑定0.0.0.0:0，绑定其他地址会导致连接失败，需要再调查一下...

**Comment by idealvin** [comment]
@Z-eddy  用最新代码试试，windows上已经绑定addr的socket再次绑定会返回`WSAEINVAL`错误，新代码已经忽略这个错误，可以试试

**Comment by Z-eddy** [comment]
刚刚出差回来，在自己电脑上测试完毕，测试通过，666
