### ISSUE TITLE
vcpkg搜出来的结果与文档不符

### ISSUE THREAD

**Issue by xiaozhu1337** [idealvin/coost#293]
![image](https://user-images.githubusercontent.com/50901869/211963012-a5913825-7922-4f14-ad74-705fdb824793.png)
文档中写的是
![image](https://user-images.githubusercontent.com/50901869/211963046-6bb88112-44c0-415e-a299-4ef7000a0a24.png)

**Comment by idealvin** [comment]
之前给 vcpkg 提了 coost 3.0，官方没更新

**Comment by xiaozhu1337** [comment]
> 之前给 vcpkg 提了 coost 3.0，官方没更新

截图里的 cocoyaxi 3.0.0 源码就是coost 3.0.0 吧？

**Comment by idealvin** [comment]
建议用 `xmake` 编译，或者用 `xrepo`。vcpkg, conan后面有空再更新
