### ISSUE TITLE
大佬~如果要只保留协程功能，其它日志什么的全都不要，hook也不要，应该怎么设置编译参数？

### ISSUE THREAD

**Issue by 1027663760** [idealvin/coost#299]
如题

**Comment by idealvin** [comment]
flag/log 是少不了的，hook可以定义全局的宏`_CO_DISABLE_HOOK`禁掉

**Comment by 1027663760** [comment]
> flag/log 是少不了的，hook可以定义全局的宏`_CO_DISABLE_HOOK`禁掉

这样就难受了，他有时候会自动写出日志

**Comment by idealvin** [comment]
> > flag/log 是少不了的，hook可以定义全局的宏`_CO_DISABLE_HOOK`禁掉
> 
> 这样就难受了，他有时候会自动写出日志

通过配置项 `min_log_level=4` 禁掉一般的日志
