### ISSUE TITLE
vs 2015编译不通过

### ISSUE THREAD

**Issue by zsxcandy** [idealvin/coost#303]
使用vs2015编译出现错误：error C2664: 'fastring &fastring::operator <<(const unsigned char *)': cannot convert argument 1 from 'const char *' to 'co::maxdp' (compiling source file ..\..\..\src\co\co.cc)
不知道是不是没有匹配这个函数
  template<typename T, _is_supported_type<god::remove_ref_t<T>> = 0>
    fastring& operator<<(T&& t)。

但是使用vs2022是可以编译通过的，是不是vs2015编译器不能编译？

**Comment by idealvin** [comment]
用master最新代码试试

**Comment by zsxcandy** [comment]
master最新代码也是一样的，我用vs2015，平台工具集是v140版本，也是编译不过，报同样的错误。。不知道是不是这个编译器的模板编译一直匹配不到这个函数template<typename T, _is_supported_type<god::remove_ref_t> = 0>
fastring& operator<<(T&& t)
这个不知道怎么搞？

**Comment by idealvin** [comment]
> master最新代码也是一样的，我用vs2015，平台工具集是v140版本，也是编译不过，报同样的错误。。不知道是不是这个编译器的模板编译一直匹配不到这个函数template<typename T, _is_supported_typegod::remove_ref_t = 0> fastring& operator<<(T&& t) 这个不知道怎么搞？

提供一下master代码编译报错的详细信息

**Comment by zsxcandy** [comment]
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
2>------ Build started: Project: co, Configuration: Debug Win32 ------
2>  Building Custom Rule D:/coost/new/coost/src/CMakeLists.txt
2>  Assembling D:\coost\new\coost\src\co\context\context_x86.asm...
2>  benchmark.cc
2>d:\coost\new\coost\include\co\god.h(138): warning C4100: 'src': unreferenced formal parameter
2>d:\coost\new\coost\include\co\god.h(138): warning C4100: 'dst': unreferenced formal parameter
2>D:\coost\new\coost\src\benchmark.cc(69): error C2664: 'text::Bold text::bold(const co::stref &) noexcept': cannot convert argument 1 from 'const char *' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(69): note: Reason: cannot convert from 'const char *' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(69): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>D:\coost\new\coost\src\benchmark.cc(69): error C2228: left of '.blue' must have class/struct/union
2>D:\coost\new\coost\src\benchmark.cc(70): error C2664: 'text::Bold text::bold(const co::stref &) noexcept': cannot convert argument 1 from 'const char [10]' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(70): note: Reason: cannot convert from 'const char [10]' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(70): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>D:\coost\new\coost\src\benchmark.cc(70): error C2228: left of '.blue' must have class/struct/union
2>D:\coost\new\coost\src\benchmark.cc(71): error C2664: 'text::Bold text::bold(const co::stref &) noexcept': cannot convert argument 1 from 'const char [10]' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(71): note: Reason: cannot convert from 'const char [10]' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(71): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>D:\coost\new\coost\src\benchmark.cc(71): error C2228: left of '.blue' must have class/struct/union
2>D:\coost\new\coost\src\benchmark.cc(72): error C2664: 'text::Bold text::bold(const co::stref &) noexcept': cannot convert argument 1 from 'const char [10]' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(72): note: Reason: cannot convert from 'const char [10]' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(72): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>D:\coost\new\coost\src\benchmark.cc(72): error C2228: left of '.blue' must have class/struct/union
2>D:\coost\new\coost\src\benchmark.cc(85): error C2664: 'text::Text text::green(const co::stref &)': cannot convert argument 1 from 'const char *' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(85): note: Reason: cannot convert from 'const char *' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(85): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>D:\coost\new\coost\src\benchmark.cc(86): error C2664: 'text::Text text::red(const co::stref &)': cannot convert argument 1 from 'fastring' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(86): note: Reason: cannot convert from 'fastring' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(86): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>D:\coost\new\coost\src\benchmark.cc(91): error C2664: 'text::Text text::red(const co::stref &)': cannot convert argument 1 from 'fastring' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(91): note: Reason: cannot convert from 'fastring' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(91): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>D:\coost\new\coost\src\benchmark.cc(102): error C2664: 'text::Text text::yellow(const co::stref &)': cannot convert argument 1 from 'fastring' to 'const co::stref &'
2>  D:\coost\new\coost\src\benchmark.cc(102): note: Reason: cannot convert from 'fastring' to 'const co::stref'
2>  D:\coost\new\coost\src\benchmark.cc(102): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>  co.cc
2>d:\coost\new\coost\include\co\god.h(138): warning C4100: 'src': unreferenced formal parameter
2>d:\coost\new\coost\include\co\god.h(138): warning C4100: 'dst': unreferenced formal parameter
2>d:\coost\new\coost\include\co\./co/sock.h(389): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'fastring' (or there is no acceptable conversion)
2>  d:\coost\new\coost\include\co\fastring.h(231): note: could be 'fastring &fastring::operator <<(const co::stref &)'
2>  d:\coost\new\coost\include\co\fastring.h(227): note: or       'fastring &fastring::operator <<(const std::string &)'
2>  d:\coost\new\coost\include\co\fastring.h(223): note: or       'fastring &fastring::operator <<(const fastring &)'
2>  d:\coost\new\coost\include\co\fastring.h(209): note: or       'fastring &fastring::operator <<(const unsigned char *)'
2>  d:\coost\new\coost\include\co\fastring.h(205): note: or       'fastring &fastring::operator <<(const signed char *)'
2>  d:\coost\new\coost\include\co\fastring.h(201): note: or       'fastring::fpstream fastring::operator <<(maxdp_t)'
2>  d:\coost\new\coost\include\co\fastring.h(653): note: or       'std::ostream &operator <<(std::ostream &,const fastring &)'
2>  d:\coost\new\coost\include\co\stref.h(35): note: or       'std::ostream &operator <<(std::ostream &,const co::stref &)'
2>  d:\coost\new\coost\include\co\./co/sock.h(389): note: while trying to match the argument list '(fastring, unsigned short)'
2>d:\coost\new\coost\include\co\./co/sock.h(403): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'fastring' (or there is no acceptable conversion)
2>  d:\coost\new\coost\include\co\fastring.h(231): note: could be 'fastring &fastring::operator <<(const co::stref &)'
2>  d:\coost\new\coost\include\co\fastring.h(227): note: or       'fastring &fastring::operator <<(const std::string &)'
2>  d:\coost\new\coost\include\co\fastring.h(223): note: or       'fastring &fastring::operator <<(const fastring &)'
2>  d:\coost\new\coost\include\co\fastring.h(209): note: or       'fastring &fastring::operator <<(const unsigned char *)'
2>  d:\coost\new\coost\include\co\fastring.h(205): note: or       'fastring &fastring::operator <<(const signed char *)'
2>  d:\coost\new\coost\include\co\fastring.h(201): note: or       'fastring::fpstream fastring::operator <<(maxdp_t)'
2>  d:\coost\new\coost\include\co\fastring.h(653): note: or       'std::ostream &operator <<(std::ostream &,const fastring &)'
2>  d:\coost\new\coost\include\co\stref.h(35): note: or       'std::ostream &operator <<(std::ostream &,const co::stref &)'
2>  d:\coost\new\coost\include\co\./co/sock.h(403): note: while trying to match the argument list '(fastring, unsigned short)'
2>d:\coost\new\coost\src\co\epoll\../sock_ctx.h(16): warning C4800: 'const uint16': forcing value to bool 'true' or 'false' (performance warning)
2>d:\coost\new\coost\src\co\scheduler.h(178): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'fastream' (or there is no acceptable conversion)
2>  d:\coost\new\coost\include\co\fastream.h(195): note: could be 'fastream &fastream::operator <<(const co::stref &)'
2>  d:\coost\new\coost\include\co\fastream.h(191): note: or       'fastream &fastream::operator <<(const fastream &)'
2>  d:\coost\new\coost\include\co\fastream.h(187): note: or       'fastream &fastream::operator <<(const std::string &)'
2>  d:\coost\new\coost\include\co\fastream.h(183): note: or       'fastream &fastream::operator <<(const fastring &)'
2>  d:\coost\new\coost\include\co\fastream.h(169): note: or       'fastream &fastream::operator <<(const unsigned char *)'
2>  d:\coost\new\coost\include\co\fastream.h(165): note: or       'fastream &fastream::operator <<(const signed char *)'
2>  d:\coost\new\coost\include\co\fastream.h(161): note: or       'fastream::fpstream fastream::operator <<(maxdp_t)'
2>  d:\coost\new\coost\src\co\scheduler.h(177): note: or       'fastream &co::operator <<(fastream &,const co::timer_id_t &)'
2>  d:\coost\new\coost\include\co\stref.h(35): note: or       'std::ostream &operator <<(std::ostream &,const co::stref &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\include\co\fastring.h(653): note: or       'std::ostream &operator <<(std::ostream &,const fastring &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\src\co\scheduler.h(178): note: while trying to match the argument list '(fastream, void *)'
2>d:\coost\new\coost\src\co\scheduler.h(274): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'fastream' (or there is no acceptable conversion)
2>  d:\coost\new\coost\include\co\fastream.h(195): note: could be 'fastream &fastream::operator <<(const co::stref &)'
2>  d:\coost\new\coost\include\co\fastream.h(191): note: or       'fastream &fastream::operator <<(const fastream &)'
2>  d:\coost\new\coost\include\co\fastream.h(187): note: or       'fastream &fastream::operator <<(const std::string &)'
2>  d:\coost\new\coost\include\co\fastream.h(183): note: or       'fastream &fastream::operator <<(const fastring &)'
2>  d:\coost\new\coost\include\co\fastream.h(169): note: or       'fastream &fastream::operator <<(const unsigned char *)'
2>  d:\coost\new\coost\include\co\fastream.h(165): note: or       'fastream &fastream::operator <<(const signed char *)'
2>  d:\coost\new\coost\include\co\fastream.h(161): note: or       'fastream::fpstream fastream::operator <<(maxdp_t)'
2>  d:\coost\new\coost\src\co\scheduler.h(177): note: or       'fastream &co::operator <<(fastream &,const co::timer_id_t &)'
2>  d:\coost\new\coost\include\co\stref.h(35): note: or       'std::ostream &operator <<(std::ostream &,const co::stref &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\include\co\fastring.h(653): note: or       'std::ostream &operator <<(std::ostream &,const fastring &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\src\co\scheduler.h(274): note: while trying to match the argument list '(fastream, co::Coroutine *)'
2>d:\coost\new\coost\src\co\scheduler.h(282): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'fastream' (or there is no acceptable conversion)
2>  d:\coost\new\coost\include\co\fastream.h(195): note: could be 'fastream &fastream::operator <<(const co::stref &)'
2>  d:\coost\new\coost\include\co\fastream.h(191): note: or       'fastream &fastream::operator <<(const fastream &)'
2>  d:\coost\new\coost\include\co\fastream.h(187): note: or       'fastream &fastream::operator <<(const std::string &)'
2>  d:\coost\new\coost\include\co\fastream.h(183): note: or       'fastream &fastream::operator <<(const fastring &)'
2>  d:\coost\new\coost\include\co\fastream.h(169): note: or       'fastream &fastream::operator <<(const unsigned char *)'
2>  d:\coost\new\coost\include\co\fastream.h(165): note: or       'fastream &fastream::operator <<(const signed char *)'
2>  d:\coost\new\coost\include\co\fastream.h(161): note: or       'fastream::fpstream fastream::operator <<(maxdp_t)'
2>  d:\coost\new\coost\src\co\scheduler.h(177): note: or       'fastream &co::operator <<(fastream &,const co::timer_id_t &)'
2>  d:\coost\new\coost\include\co\stref.h(35): note: or       'std::ostream &operator <<(std::ostream &,const co::stref &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\include\co\fastring.h(653): note: or       'std::ostream &operator <<(std::ostream &,const fastring &)' [found using argument-dependent lookup]
2>  d:\coost\new\coost\src\co\scheduler.h(282): note: while trying to match the argument list '(fastream, co::Coroutine *)'

**Comment by zsxcandy** [comment]
Visual Studio 2015 Version 14.025420.01 Update 3版本

**Comment by zsxcandy** [comment]
老哥有空帮忙看看呀

**Comment by idealvin** [comment]
有空看看

**Comment by shxygray** [comment]
```
template <typename S, god::enable_if_t<god::is_c_str<god::remove_ref_t<S>>(), int> = 0>
void Func() {}

const char* str = "test";
Func(str);
```
一样的问题，这个模板推导失败了, vs2015
error C2783: “void Func2(S &&)”: 未能为“__formal”推导 模板 参数

```
template <typename S, god::enable_if_t<std::is_same<S, const char*>::value, int> = 0>
void Func2(S str)
{
}
```
用这个是编译过了， 但是也不能加&&

**Comment by idealvin** [comment]
```cpp
template <typename S, god::enable_if_t<god::is_c_str<god::remove_ref_t<S>>(), int> = 0>
void Func(S&&) {}

const char* str = "test";
Func(str);
```

上面这个是什么原因推导失败？打印 `god::is_same<god::remove_ref_t<decltype(str)>, const char*>()` 看看

**Comment by shxygray** [comment]
试了一下vs2022的版本编译没问题

这是2015版本的
```
constexpr bool check = god::is_same<god::remove_ref_t<decltype(str)>, const char*>();       // true
using S = god::enable_if_t<god::is_c_str<god::remove_ref_t<decltype(str)>>(), int>;
S i;
printf("check:%d, type:%s\n", check, typeid(S).name());     // 1, int

// 就这部分编译不过
template <typename S, god::enable_if_t<god::is_c_str<god::remove_ref_t<S>>(), int> = 0>
void Func(S str)
{
}
const char* str = "test";
Func(str);
```
报错信息应该就是模板没匹配到
error C2672: “Func”: 未找到匹配的重载函数
error C2783: “void Func(S)”: 未能为“__formal”推导 模板 参数
note: 参见“Func”的声明

**Comment by shxygray** [comment]
找到问题了,  是因为 god::remove_ref_t<S>>(), 2015版本括号的问题
直接用 typename std::remove_cv<S>::type 编译可以

**Comment by idealvin** [comment]
> 找到问题了, 是因为 `god::remove_ref_t<S>>()` 2015版本括号的问题 直接用 `typename std::remove_cv<S>::type` 编译可以

这可能是编译器实现有 bug

**Comment by idealvin** [comment]
> 找到问题了, 是因为 `god::remove_ref_t<S>>()` 2015版本括号的问题 直接用 `typename std::remove_cv<S>::type` 编译可以

修改后 coost 能用 vs2015 编译成功吗？

**Comment by shxygray** [comment]
别的地方还有一些问题
fastring 的 operator<< 重载编译也报错了， 我暂时用2022版本的了

**Comment by zsxcandy** [comment]
> 别的地方还有一些问题 fastring 的 operator<< 重载编译也报错了， 我暂时用2022版本的了

不止fastring有问题，fastream里面的operator<<重载编译也有问题，也是那个模板推导失败导致的，vs2015应该不支持这样的，只能用更高版本的编译器了

**Comment by idealvin** [comment]
@shxygray @zsxcandy 

下面这段代码在 vs2015 上能编译通过么？输出值结果是？
```cpp
#include <iostream>
#include <string>
#include <type_traits>


#define DEF_has_method(f) \
namespace god { \
template<typename _T_> \
struct _has_method_##f { \
    struct _R_ { int _[2]; }; \
    template<typename _X_> static int test(decltype(&_X_::f)); \
    template<typename _X_> static _R_ test(...); \
    enum { value = sizeof(test<typename std::remove_reference<_T_>::type>(0)) == sizeof(int) }; \
}; \
\
template<typename _T_> \
constexpr bool has_method_##f() noexcept { return _has_method_##f<_T_>::value; } \
}

DEF_has_method(c_str);


int main(int argc, char** argv) {
    bool x = god::has_method_c_str<std::string>();
    std::cout << x << std::endl;
    return 0;
}
```

**Comment by shxygray** [comment]
可以, 为true

**Comment by idealvin** [comment]
> 可以, 为true

@shxygray 
好的，感谢！换成下面的代码呢？结果是多少？

```cpp
#include <iostream>
#include <string>
#include <type_traits>

template<typename T>
using rm_ref_t = typename std::remove_reference<T>::type;

#define DEF_has_method(f) \
namespace god { \
template<typename _T_> \
struct _has_method_##f { \
    struct _R_ { int _[2]; }; \
    template<typename _X_> static int test(decltype(&_X_::f)); \
    template<typename _X_> static _R_ test(...); \
    enum { value = sizeof(test<rm_ref_t<_T_>>(0)) == sizeof(int) }; \
}; \
\
template<typename _T_> \
constexpr bool has_method_##f() noexcept { return _has_method_##f<_T_>::value; } \
}

DEF_has_method(c_str);
DEF_has_method(hello);


int main(int argc, char** argv) {
    std::cout << god::has_method_c_str<std::string>() << ' ';
    std::cout << god::has_method_hello<std::string>() << std::endl;
    return 0;
}
```

**Comment by shxygray** [comment]
@idealvin true, false

**Comment by idealvin** [comment]
@shxygray 
ok，感谢！master 代码最近更新了，可以试试在 vs2015 上能不能编译

```sh
xmake b unitest
xmake r unitest
```

**Comment by shxygray** [comment]
感谢, 大佬辛苦, 有空我试下
