### ISSUE TITLE
请问一下共享栈疑问

### ISSUE THREAD

**Issue by bigbao9494** [idealvin/coost#306]
”共享栈，同一线程中的协程共用若干个栈(大小默认为 1MB)，内存占用低。“
是指所有的协程都使用物理线程的栈？
创建协程数量是否有限制？
协程的使用是否会出现栈溢出问题？
是否有以下缺点：
      协程调度产生的局部变量都在共享栈上, 一旦新的协程运行后共享栈中的数据就会被覆盖, 先前协程的局部变量也就不再有效, 进而无法实现参数传递、嵌套调用等高级协程交互.

**Comment by idealvin** [comment]
1、不是
2、协程数量只受物理资源(主要是内存)限制
3、栈大小默认为 1M，一般不会溢出
4、不同协程之间注意不共享局部变量即可
