### ISSUE TITLE
新开一个贴，续问一下上次问题

### ISSUE THREAD

**Issue by bigbao9494** [idealvin/coost#309]
[https://github.com/idealvin/coost/issues/307](url)
麻烦还有一个问题
问题2用法问题，是示例中原始代码，你是说那个示例写得有问题？
测试了问题2中示例echo，在LINUX下没有问题，在WINDOWS平台下的问题，可能和WIN下的IO相关吧。
问题4：coost的协程和网络库相关是否有工程应用？
还有就是问题3，正确姿势是怎样的？

**Comment by idealvin** [comment]
用3.0.1版本试试
