### ISSUE TITLE
使用Thread提示未定义

### ISSUE THREAD

**Issue by troycheng** [idealvin/coost#310]
参考[文档](https://coostdocs.github.io/cn/co/thread/)中使用Thread类，提示未定义，搜源代码也未找到Thread相关定义，看unitest中使用的也是std::thread，请问是使用姿势不对还是这块儿的文档需要更新，感谢

**Comment by idealvin** [comment]
> 参考[文档](https://coostdocs.github.io/cn/co/thread/)中使用Thread类，提示未定义，搜源代码也未找到Thread相关定义，看unitest中使用的也是std::thread，请问是使用姿势不对还是这块儿的文档需要更新，感谢

最近删掉了Thread，文档暂时没有更新

**Comment by idealvin** [comment]
后面有空更新文档

**Comment by idealvin** [comment]
Thread 与 `std::thread` 功能是一样的，直接用 std 版本
