### ISSUE TITLE
在windows下，使用vue3构建的web使用(so::easy)搭建静态web server失败

### ISSUE THREAD

**Issue by AKanTam** [idealvin/coost#320]
环境是：win10，vs2019，C++14，使用的是从vcpkg上直接拉下来的3.0库
尝试过哈希路由和历史路由，都是请求都为200但是打开空白的情况，同样的web使用mongoose库一切正常
然后我尝试使用mongoose官方给的测试web文件使用coost库搭建静态web server，也是一样的情况
![image](https://user-images.githubusercontent.com/40015135/233757483-f5ab9d58-0bd1-424f-8f47-01c66f21f439.png)
![image](https://user-images.githubusercontent.com/40015135/233757500-acb9c662-cd1b-4da0-b4d0-49641ce468ec.png)

**Comment by idealvin** [comment]
`dist` 路径是对的吗？

**Comment by AKanTam** [comment]
dist是放在可执行文件同一目录吗，我试过"/dist"和"./dist"，都不行
主要是页面文件，网页图标和标题都加载出来了，就是中间的内容是空白的而已

**Comment by AKanTam** [comment]
![image](https://user-images.githubusercontent.com/40015135/233760017-625b970d-76d0-4094-ad0a-e4e552eb6ff1.png)
dist目录跟.sln是同一级目录的

**Comment by idealvin** [comment]
`dist`压缩一下有多大，不大的话，可以发出来，我这边试试

**Comment by AKanTam** [comment]
[dist.zip](https://github.com/idealvin/coost/files/11300208/dist.zip)
只是个测试的小页面，源文件是rar格式压缩的，但rar传不上来，我后缀直接改成zip了

**Comment by idealvin** [comment]
压缩成zip的再传

**Comment by AKanTam** [comment]
[dist.zip](https://github.com/idealvin/coost/files/11300222/dist.zip)
同样的代码和dist文件，我使用Linux(ubantu20.04)重新编译，运行后提示`check failed: x != (uint32)-1!`，然后aborted了

**Comment by idealvin** [comment]
> [dist.zip](https://github.com/idealvin/coost/files/11300222/dist.zip) 我在Linux（ubantu 20.04）上也尝试了一下，同样的是页面文件，网页图标和标题都能加载出来，但是网页的具体内容是空白的

`index.html` 文件 body 部分本来就是空的，没有内容...

**Comment by AKanTam** [comment]
vue打包生成的文件就是这样，具体前端实现我也不是很懂，不过这个我用Live Server和mongoose库都可以实现正常功能，不过因为现在coost用的比较多，所以希望可以用vue+coost搭建一些简单的网站，如果是这样的话可能coost和vue不兼容，感谢您的回复

**Comment by idealvin** [comment]
这个可能是打包配置的问题，参考[这里](https://blog.csdn.net/weixin_28689507/article/details/117848644)试试

**Comment by AKanTam** [comment]
> 这个可能是打包配置的问题，参考[这里](https://blog.csdn.net/weixin_28689507/article/details/117848644)试试

我配置是按着这个来的，这个空白的情况我之前在使用别的web server的时候也是，但现在照着这个配置改好了之后，Live Server和mongoose都跑通了，只有coost还是空白的😂

**Comment by xiaoshanlin000** [comment]
文件 Content-Type 没有对应返回吧。

**Comment by xiaoshanlin000** [comment]
返回 Content-Type 就正常了。
![WX20230710-211533@2x](https://github.com/idealvin/coost/assets/5867735/6c7a88d0-a2cd-420f-9521-278b1f557d33)
![WX20230710-211547@2x](https://github.com/idealvin/coost/assets/5867735/093d6285-c5ea-427b-ad00-d6b8100f9455)

**Comment by AKanTam** [comment]
> 返回 Content-Type 就正常了。 ![WX20230710-211533@2x](https://user-images.githubusercontent.com/5867735/252351191-6c7a88d0-a2cd-420f-9521-278b1f557d33.png) ![WX20230710-211547@2x](https://user-images.githubusercontent.com/5867735/252351228-093d6285-c5ea-427b-ad00-d6b8100f9455.png)

感谢
