### ISSUE TITLE
如何打印格式化的 log 

### ISSUE THREAD

**Issue by Heafei** [idealvin/coost#328]
格式化log是不是得先格式化为字符串后，再打印？

**Comment by idealvin** [comment]
可以重载 `fastream& operator<<(fastream&, const X&)`，然后用 `LOG << X` 打印

**Comment by youngday** [comment]
现在好多log都在增加fmtlib，或者直接fmt::format data 后打印，可以直接打印vector等

**Comment by idealvin** [comment]
vector 可以直接 `LOG << vector`

**Comment by idealvin** [comment]
v3.0.1中，`co::print()`，`LOG` 都可以直接打印 vector 等容器。
