### ISSUE TITLE
fastream 在不同平台测试比 snprintf 快 10~30 倍左右, 但是如何快速格式化字符串为faststring 类呢

### ISSUE THREAD

**Issue by youyuanshanren** [idealvin/coost#329]
经常遇到的是 void output(const char* format, ...) 这种类型的函数，含有不定参数，如果不使用vsnprintf  这类的参数，如何快速转换为faststring 或者 fastream 类型呢

**Comment by idealvin** [comment]
`fastring::cat()` 或 `fastream::cat()` 可以接受任意数量的参数

**Comment by cailei77** [comment]
cat()函数似乎不能格式化字符串啊？如何能够做到类似sprintf的功能呢？
