### ISSUE TITLE
json模块功能增强

### ISSUE THREAD

**Issue by mankouzhuya** [idealvin/coost#334]
作者可以考虑一下把现有的json功能增强一下嘛，比如json字符串转struct，struct转json字符串这些功能，这些功能非常实用。参考: 
 https://github.com/xyz347/xpack

**Comment by idealvin** [comment]
有更好的实现方法吗？

**Comment by mankouzhuya** [comment]
https://github.com/qicosmos/iguana  也实现了类似的序列化和反序列化功能

**Comment by momooy** [comment]
xpack巨好用

**Comment by idealvin** [comment]
@mankouzhuya 

coost 中 JSON RPC 框架中的 [gen](https://github.com/idealvin/coost/tree/master/gen) 工具，可以顺便支持所需功能。

在 `xx.proto` 文件中像如下定义 JSON 结构：
```proto
// supported base types:
//   bool, int, int32, uint32, int64, uint64, double, string
object X {
    string api
    data {  // anonymous object, field name can be put ahead
        bool b
        int i
        double d
        [int] ai   // array of int
        ao [{      // array of anonymous object
            int v
            string s
        }]
    }
}
```

直接 `gen xx.proto` 就可以生成所需要的代码，可以用 master 最新代码试试。

**Comment by idealvin** [comment]
参考示例 [j2s](https://github.com/idealvin/coost/tree/master/test/j2s)，`gen j2s.proto` 即可生成所需代码

**Comment by mankouzhuya** [comment]
OK，我现在用的xpack ,我后面有机会试试里面自带的json工具
