### ISSUE TITLE
json是否支持多种编码？

### ISSUE THREAD

**Issue by eVen-p** [idealvin/coost#337]
有些c++ json库会对字符编码有一定的限制，比如说nlohmann::json，有的库就支持（内部）转换编码，比如说rapidJson。

想问一下coost的json在这一方面的支持如何？

**Comment by idealvin** [comment]
不支持编码转换

**Comment by eVen-p** [comment]
那会像nlohmann库主要支持UTF8一样限制于一种特定的编码吗
