### ISSUE TITLE
mkconf 导出参数默认值带有“//”时的问题

### ISSUE THREAD

**Issue by lzhkui** [idealvin/coost#339]
## 代码示例
```c++
// xxx.cpp
DEF_string(jwt_issuer, "http://www.example.cn", "jwt issuer");
... ...

// mkconf生成的xxx.conf 如下
# jwt issuer
jwt_issuer = http://www.example.cn
... ...
```

如上示例，参数的默认值含有 `//`，flag解析结果只保留了`http:`，我没具体查代码，但是后面的应该是被当作注释省略了

## 解决方法
一个可选的解决方法是，在mkconf生成配置参数时，对含有 注释符 的默认值，增加双引号包裹，如下所示，
``` cpp
# jwt issuer
jwt_issuer = "http://www.example.cn"
```
加上双引号后，测试是可以完整解析的

### 错误结果
![image](https://github.com/idealvin/coost/assets/9360274/66ba68e5-7eb1-47a7-aa63-3f7fd29f8428)

### 正确结果
![image](https://github.com/idealvin/coost/assets/9360274/d9e0ad03-0715-458f-beb0-c5cb5418eea0)

**Comment by idealvin** [comment]
@lzhkui  
感谢指出，已经提交[修复](https://github.com/idealvin/coost/commit/5b0d592cf25c593c4489f160ee6fe50bcbbf23a5)了，可以试试

**Comment by lzhkui** [comment]
赞👍
