### ISSUE TITLE
用wait_group执行计算图

### ISSUE THREAD

**Issue by leezear2022** [idealvin/coost#342]
你好，我用wait_group写一个计算图时遇到了问题，func1和func2依赖于func0，func3依赖于func1和func2。
`#include "co/co.h"
#include "co/cout.h"

int main(int argc, char **argv) {
    flag::parse(argc, argv);

    co::vector<co::wait_group> wgs = {co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(2)};

    wgs[0].done();

    go([&]() {
        wgs[0].wait();
        co::print("func0");
        wgs[1].done();
        wgs[2].done();
    });

    go([&]() {
        wgs[1].wait();
        // LOG << "hello world";
        co::print("func1");
        wgs[3].done();
    });

    go([&]() {
        wgs[2].wait();
        co::print("func2");
        wgs[3].done();
    });

    go([&]() {
        wgs[3].wait();
        co::print("func3");
        wgs[3].done();
    });

    return 0;
}`

在初始化时就报错`    co::vector<co::wait_group> wgs = {co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(2)};`

报错位置在这里：co::wait_group::wait god.h:15
co::xx::Function0<main::{lambda()#3}>::run() 0x0000555555565ffc
co::xx::Sched::main_func sched.cc:67
__entry context_x64.S:264
<unknown> 0x0000000000000000    
请问我这样写有问题吗？

**Comment by leezear2022** [comment]
hi，我又改写了一下，发现可以跑通了，感谢你的轮子！！

`
#include "co/co.h"
#include "co/cout.h"

int main(int argc, char **argv) {
    flag::parse(argc, argv);

    co::vector<co::wait_group> wgs = {co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(1),
                                      co::wait_group(2),
                                      co::wait_group(1)};


    go([&]() {
        co::print("func0");
        wgs[1].done();
        wgs[2].done();
    });

    go([&]() {
        wgs[1].wait();
        co::print("func1");
        wgs[3].done();
    });

    go([&]() {
        wgs[2].wait();
        co::print("func2");
        wgs[3].done();
    });

    go([&]() {
        wgs[3].wait();
        co::print("func3");
        wgs[4].done();
    });

    wgs[4].wait();
    co::print("---start--");
    wgs[0].done();
    co::print("---end--");

    return 0;
}
`
ps: 请问还有没有更优雅的写法么:P？

**Comment by idealvin** [comment]
就这样
