### ISSUE TITLE
关于coost文档付费的声明

### ISSUE THREAD

**Issue by idealvin** [idealvin/coost#344]
尊敬的各位coost用户：

大家好，我是 Alvin，感谢大家长期以来的支持！

为使coost项目得到更好的发展，决定对 coost 文档收取少量费用，请查看[官方文档声明](https://coostdocs.gitee.io/cn/about/co/#%e6%96%87%e6%a1%a3%e4%bb%98%e8%b4%b9%e5%a3%b0%e6%98%8e)。再次感谢各位的理解与支持！

Alvin 敬上
2023/9/23

**Comment by heheda123123** [comment]
以后咋看文档？交了费发离线文档吗？

**Comment by idealvin** [comment]
> 以后咋看文档？交了费发离线文档吗？

这两年，国内的一些个人维护的知名开源项目陆续停更了。没有收入，项目基本上很难维持下去。

一次性收取少量费用即可永久免费使用的模式基本上也走不通，没有持续性收入，项目也维持不下去。

文档付费不行的话，后面可能改成项目付费。这里可以探讨一下国内开源项目的出路..

**Comment by heheda123123** [comment]
前端的可能可以，像vue的作者就财务自由了，c++这种项目比较难

**Comment by heheda123123** [comment]
啥时候开始收费？意思是之后文档部分会删掉嘛？

**Comment by heheda123123** [comment]
意思还是等用库的人主动捐赠？
不是强制性收费的话建议措辞改一下

**Comment by idealvin** [comment]
文档就放在那里，使用的就付费

**Comment by piperoc** [comment]
I'm not sure I understand all this. I went to the documentation link (the English version) and I wasn't asked to pay, it just shows the content. 

The link I follow is the one on the README: https://coostdocs.github.io/en/about/co/ .
It does not mention the need to pay or a price. 

Thank you for clarifying/

**Comment by heheda123123** [comment]
Only Chinese doc have this content.
