### ISSUE TITLE
IOS旧设备上存在加载库就内存申请奔溃现象

### ISSUE THREAD

**Issue by optimal16** [idealvin/coost#345]
当老旧版本的ipad加载该静态库时，出现了talloc申请内存奔溃。

![WX20231017-223958@2x](https://github.com/idealvin/coost/assets/21096083/556bc537-fe99-454b-a721-049fe53ece66)

请问如何解决。
@idealvin

**Comment by optimal16** [comment]
仅仅是引用这个库，写了一行LOG，发现了奔溃。
![image](https://github.com/idealvin/coost/assets/21096083/978e8616-c6d1-45fc-a9fa-215b6173210e)

**Comment by idealvin** [comment]
已提交修复代码
