### ISSUE TITLE
windows下使用CMake GUI进行配置，没有BUILD_SHARED_LIBS 选项

### ISSUE THREAD

**Issue by JiadiLee** [idealvin/coost#352]
windows下使用CMake GUI进行配置，没有BUILD_SHARED_LIBS 选项：
![1704268384075](https://github.com/idealvin/coost/assets/107230195/b4c90abc-287e-4d5a-b9d9-a2e5553876c7)

**在CmakeLists.txt 中加入"option(BUILD_SHARED_LIBS "build with shared libs" OFF)" 语句可解决，但在VS2022 编译的时候有报错：g_tid:具有线程存储持续时间的数据可能没有dl接口**，该变量是使用__thread声明的。 VS中 thread 变量的地址在运行时前未知，因此不能链接到 DLL 导入或导出，此问题需要怎么解决？
![1704269344358](https://github.com/idealvin/coost/assets/107230195/2706f0a8-1580-4df2-bc51-c9812c25090f)

**Comment by idealvin** [comment]
@JiadiLee 
master最新代码解决了 `g_tid` 报错问题

**Comment by JiadiLee** [comment]
> @JiadiLee master最新代码解决了 `g_tid` 报错问题

更新代码后问题已解决，感谢回复！
