### ISSUE TITLE
co::shared & co::unique 存在问题

### ISSUE THREAD

**Issue by ChrisCatCP** [idealvin/coost#360]
目前的实现会直接实例化一个T 
```c++
struct S { T o; size_t n; };
//构造S的时候会实例化T  当T为纯虚基类的时候无法实例化
```

**Comment by ChrisCatCP** [comment]
并且这里的n我也不理解存在什么作用

**Comment by idealvin** [comment]
修复了，见 [这里](https://github.com/idealvin/coost/commit/0e89c366f707ff4ca4738f879fd5e6934bc57cc4)

**Comment by idealvin** [comment]
> 并且这里的n我也不理解存在什么作用

释放内存需要知道内存大小

**Comment by ChrisCatCP** [comment]
> > 并且这里的n我也不理解存在什么作用
> 
> 释放内存需要知道内存大小

大小不就是sizeof(S)吗。。。

**Comment by ChrisCatCP** [comment]
并且我发现存在内存泄漏，运行环境是centos6/7，我看到有人提交了相同的issues我就不提交了
